name: badminton_booking_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_messaging: ^14.7.10


  # UI & Fonts
  google_fonts: ^6.2.1
  table_calendar: ^3.0.9
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.0.0

  # Network & Storage
  http: ^1.2.2
  shared_preferences: ^2.0.9
  socket_io_client: ^2.0.3+1

  # UI helpers
  fluttertoast: ^8.0.9
  qr_flutter: ^4.0.0
  image_picker: ^1.0.0

  # Notifications & Timezone
  flutter_local_notifications: ^17.2.3
  flutter_timezone: ^4.1.1
  timezone: ^0.9.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/googleicon.png
    - assets/images/shuttle.png
    - assets/images/court1.png
    - assets/images/court2.webp
    - assets/images/booking.jpg
    - assets/images/gift.jpg
    - assets/
